MyHealthBlog/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using MyHealthBlog.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyHealthBlog.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {

            return View();
        }
       
        public IActionResult RouteToCrud(CrudRoute CrudObejct)
        {
            return RedirectToAction(CrudObejct.Action, CrudObejct.Controller);
        }
        
    }
}

MyHealthBlog/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Mvc;
using MyHealthBlog.Data.Repos;
using MyHealthBlog.Domain;
using MyHealthBlog.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyHealthBlog.Controllers
{
    public class ArticleController : Controller
    {
        //private readonly GenericRepo<FoodCategory> _genericRepo;
        private readonly ArticleRepo _articleRepo;
        public ArticleController()
        {
            _articleRepo = new ArticleRepo();
            //_genericRepo = new GenericRepo<FoodCategory>();
        }
        [HttpGet]
        public IActionResult Create()
        {
           Article article = new Article();

            return View(article);
        }
        [HttpPost]
        public IActionResult Create(Article article)
        {
            if (article == null)
            {
                return NotFound("Could not create object.");
            }
            _articleRepo.Create(article);
            _articleRepo.Save();

            return RedirectToAction("Index", "Home");
        }

        public IActionResult Delete()
        {
            FoodList foodlist = new FoodList();
            foodlist.Articles = _articleRepo.GetAllArticles;

            return View(foodlist);
        }

        public IActionResult Delete1(int id)
        {
            Article article = _articleRepo.GetArticleById(id);

            if (article == null)
            {
                return NotFound("Something went wrong");
            }
            _articleRepo.Delete(article);
            _articleRepo.Save();

            return RedirectToAction("Index", "Home");
        }

        public IActionResult Update()
        {
            FoodList foodlist = new FoodList();
            foodlist.Articles = _articleRepo.GetAllArticles;
            return View(foodlist);
        }
        [HttpGet]
        public IActionResult UpdateForm(int id)
        {
            Article article = _articleRepo.GetArticleById(id);
            return View(article);
        }
        [HttpPost]
        public IActionResult UpdateForm(Article article)
        {
            if (article == null)
            {
                return NotFound("Something went wrong");
            }
            _articleRepo.Update(article);
            _articleRepo.Save();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult GetDetails()
        {
            return View();
        }


        public IActionResult Details(Article article)
        {
            Article article1 = _articleRepo.NameExists(article.HeadLine);
            if (article1 == null)
            {
                return NotFound("Something went wrong");
            }

            return View(article1);
        }
    }
}

MyHealthBlog/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using MyHealthBlog.Domain;
using MyHealthBlog.ViewModels;
using MyHealthBlog.Data.Repos;

namespace MyHealthBlog.Controllers
{
    public class CategoryController : Controller
    {

        //private readonly GenericRepo<FoodCategory> _genericRepo;
        private readonly CategoryRepo _categoryRepo;
        public CategoryController()
        {
            _categoryRepo = new CategoryRepo();
            //_genericRepo = new GenericRepo<FoodCategory>();
        }
        [HttpGet]
        public IActionResult Create()
        {
            FoodCategory category = new FoodCategory();

            return View(category);
        }
        [HttpPost]
        public IActionResult Create(FoodCategory category)
        {
            if (category == null)
            {
                return NotFound("Could not create object.");
            }
            _categoryRepo.Create(category);
            _categoryRepo.Save();

            return RedirectToAction("Index", "Home");
        }

        public IActionResult Delete()
        {
            FoodList foodlist = new FoodList();
            foodlist.Categorys = _categoryRepo.GetAllCategorys;

            return View(foodlist);
        }

        public IActionResult Delete1(int id)
        {
            FoodCategory category = _categoryRepo.GetCategoryById(id);

            if (category == null)
            {
                return NotFound("Something went wrong");
            }
            _categoryRepo.Delete(category);
            _categoryRepo.Save();

            return RedirectToAction("Index", "Home");
        }
    }
}

MyHealthBlog/Controllers/FoodController.cs
using Microsoft.AspNetCore.Mvc;
using MyHealthBlog.Domain;
using MyHealthBlog.Data.Repos;
using MyHealthBlog.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MyHealthBlog.Controllers
{
    public class FoodController : Controller
    {
        private readonly FoodRepo _foodRepo;

        public FoodController(/*IFoodRepo foodRepo*/)
        {
            _foodRepo = new FoodRepo();
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            FoodObject food = new FoodObject();

            return View(food);
        }
        [HttpPost]
        public IActionResult Create(FoodObject food)
        {

            _foodRepo.NameExists(food.Name);

            if (food == null)
            {
                return NotFound("Could not create object.");
            }

            _foodRepo.Create(food);
            _foodRepo.Save();

            return RedirectToAction("Index", "Home");
        }

        public IActionResult Delete()
        {
            FoodList foodlist = new FoodList();
            foodlist.ListOfFoods = _foodRepo.GetAllFoodObjects;

            return View(foodlist);
        }

        public IActionResult Delete1(int id)
        {
            FoodObject food = _foodRepo.GetFoodById(id);

            if (food == null)
            {
                return NotFound("Something went wrong");
            }
            _foodRepo.Delete(food);
            _foodRepo.Save();

            return RedirectToAction("Index", "Home");
        }

        public IActionResult Update()
        {
            FoodList foodlist = new FoodList();
            foodlist.ListOfFoods = _foodRepo.GetAllFoodObjects;
            return View(foodlist);
        }
        [HttpGet]
        public IActionResult UpdateForm(int id)
        {
            FoodObject food = _foodRepo.GetFoodById(id);
            return View(food);
        }
        [HttpPost]
        public IActionResult UpdateForm(FoodObject food)
        {
            if (food == null)
            {
                return NotFound("Something went wrong");
            }
            _foodRepo.Update(food);
            _foodRepo.Save();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult GetDetails()
        {
            return View();
        }
            

        public IActionResult Details(FoodObject foodObject)
        {
            FoodObject food = _foodRepo.NameExists(foodObject.Name);
            if(food == null)
            {
                return NotFound("Something went wrong");
            }

            return View(food);
        }
    }
}

MyHealthBlog/Views/Shared/ArticleThumbnail.cshtml
@using MyHealthBlog.Domain
@model Article

<div class="col-sm-4 col-lg-4 col-md-4">
    <h4>@Model.HeadLine</h4>
    <div class="thumbnail">
        <div>
            <p class="button">
                <a class="btn btn-primary" asp-controller="Article" asp-action="Delete1"
                   asp-route-id="@Model.Id">Delete</a>
            </p>
        </div>
    </div>
</div>

MyHealthBlog/Views/Shared/ArticleUpdate.cshtml
@using MyHealthBlog.Domain
@model Article

<div class="col-sm-4 col-lg-4 col-md-4">
    <h4>@Model.HeadLine</h4>
    <div class="thumbnail">
        
        <br />
        <div>
            <p class="button">
                <a class="btn btn-primary" asp-controller="Article" asp-action="UpdateForm"
                   asp-route-id="@Model.Id">Update</a>
            </p>
        </div>
    </div>
</div>

MyHealthBlog/Views/Shared/CategoryThumbnail.cshtml
@using MyHealthBlog.Domain
@model FoodCategory

<div class="col-sm-4 col-lg-4 col-md-4">
    <h4>@Model.FoodType</h4>
    <div class="thumbnail">
        <img src="@Model.ImgUrl" alt="">
        <div>
            <p class="button">
                <a class="btn btn-primary" asp-controller="Category" asp-action="Delete1"
                   asp-route-id="@Model.Id">Delete</a>
            </p>
        </div>
    </div>
</div>

MyHealthBlog/Views/Shared/CategoryUpdateList.cshtml
@using MyHealthBlog.Domain
@model FoodCategory

<div class="col-sm-4 col-lg-4 col-md-4">
    <h4>@Model.FoodType</h4>
    <div class="thumbnail">
        <img src="@Model.ImgUrl" alt="" height="350" width="600">
        <br />
        <div>
            <p class="button">
                <a class="btn btn-primary" asp-controller="Category" asp-action="UpdateForm"
                   asp-route-id="@Model.Id">Update</a>
            </p>
        </div>
    </div>
</div>

MyHealthBlog/Views/Shared/FoodMin.cshtml
@using MyHealthBlog.Domain
@model FoodObject

<div class="col-sm-4 col-lg-4 col-md-4">
    <h4>@Model.Name</h4>
    <div class="thumbnail">
        <img src="@Model.ImageUrl" alt="">
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary" asp-controller="Food" asp-action="Delete1"
                   asp-route-id="@Model.Id">Delete</a>
            </p>
            
            <p class="button" >
                <a class="btn btn-primary" asp-controller="Food" asp-action="Update"
                   asp-route-id="@Model.Id">Update</a>
            </p>
            
        </div>
    </div>
</div>

MyHealthBlog/Views/Shared/FoodUpdateList.cshtml
@using MyHealthBlog.Domain
@model FoodObject

<div class="col-sm-4 col-lg-4 col-md-4">
    <h4>@Model.Name</h4>
    <div class="thumbnail">
        <img src="@Model.ImageUrl" alt="">
        <div>
            <p class="button">
                <a class="btn btn-primary" asp-controller="Food" asp-action="UpdateForm"
                   asp-route-id="@Model.Id">Update</a>
            </p>
        </div>
    </div>
</div>

MyHealthBlog/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyHealthBlog</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MyHealthBlog</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Admin" asp-action="Index">Admin</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - MyHealthBlog</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>